name: Update MSRV

on:
  push: 
    branches:
      - "master"

jobs:
  update_msrv: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2

      - name: Download cargo-msrv
        run: cargo install cargo-msrv

      - name: Get MSRV
        working-directory: ./lib
        run: echo "MSRV=$(cargo msrv --output-format json | tail -n 1 | jq '. | .msrv' --raw-output)" >> $GITHUB_ENV

      - name: Update badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ddf24204fe14719ca73916b3d9130861
          filename: qr-rs-lib_msrv.json
          label: MSRV
          message: ${{ env.MSRV }}
          color: 32ca55
          labelColor: 353d46
