name: Create a release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2

      - name: Prepare
        run: cargo install cargo-release

      - name: Login to Crates.io
        run: cargo login ${{ secrets.CRATESIO_TOKEN }}

      - name: Crates.io
        working-directory: ./lib
        run: cargo release publish --execute --no-confirm

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker - x86
        run: |
          docker build -t antoniosbarotsis/qr-rs:${{ inputs.version }} .
          docker push antoniosbarotsis/qr-rs:${{ inputs.version }}
