# TODO check that this works
name: Release server crate
on:
  push:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        type: string

jobs:
  publish_server:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker - x86
        run: |
          docker build -t antoniosbarotsis/qr-rs:${{ inputs.version }} .
          docker push antoniosbarotsis/qr-rs:${{ inputs.version }}
