name: Release lib crate
on:
  workflow_dispatch:

jobs:
  publish_lib:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v1

      - name: Prepare
        run: cargo install cargo-release

      - name: Login to Crates.io
        run: cargo login ${{ secrets.CRATESIO_TOKEN }}

      - name: Publish lib
        working-directory: ./lib
        run: cargo release publish --execute --no-confirm
